import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'bn' | 'ta' | 'te' | 'mr' | 'gu' | 'kn' | 'ml' | 'pa';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'dashboard': 'Dashboard',
    'appointments': 'Appointments',
    'prescriptions': 'Prescriptions',
    'settings': 'Settings',
    'logout': 'Logout',
    'save': 'Save',
    'cancel': 'Cancel',
    'edit': 'Edit',
    'delete': 'Delete',
    'view': 'View',
    'status': 'Status',
    'date': 'Date',
    'time': 'Time',
    'doctor': 'Doctor',
    'patient': 'Patient',
    'name': 'Name',
    'email': 'Email',
    'phone': 'Phone',
    'address': 'Address',
    'emergency_contact': 'Emergency Contact',
    'relationship': 'Relationship',
    'notifications': 'Notifications',
    'security': 'Security',
    'profile': 'Profile',
    'change_password': 'Change Password',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'confirm_password': 'Confirm Password',
    'update_password': 'Update Password',
    'two_factor_auth': 'Two-Factor Authentication',
    'enable_2fa': 'Enable 2FA',
    'language': 'Language',
    'select_language': 'Select Language',
  },
  hi: {
    // Common
    'dashboard': 'डैशबोर्ड',
    'appointments': 'अपॉइंटमेंट',
    'prescriptions': 'प्रिस्क्रिप्शन',
    'settings': 'सेटिंग्स',
    'logout': 'लॉग आउट',
    'save': 'सहेजें',
    'cancel': 'रद्द करें',
    'edit': 'संपादित करें',
    'delete': 'हटाएं',
    'view': 'देखें',
    'status': 'स्थिति',
    'date': 'तारीख',
    'time': 'समय',
    'doctor': 'डॉक्टर',
    'patient': 'मरीज़',
    'name': 'नाम',
    'email': 'ईमेल',
    'phone': 'फोन',
    'address': 'पता',
    'emergency_contact': 'आपातकालीन संपर्क',
    'relationship': 'संबंध',
    'notifications': 'सूचनाएं',
    'security': 'सुरक्षा',
    'profile': 'प्रोफ़ाइल',
    'change_password': 'पासवर्ड बदलें',
    'current_password': 'वर्तमान पासवर्ड',
    'new_password': 'नया पासवर्ड',
    'confirm_password': 'पासवर्ड की पुष्टि करें',
    'update_password': 'पासवर्ड अपडेट करें',
    'two_factor_auth': 'दो-कारक प्रमाणीकरण',
    'enable_2fa': '2FA सक्षम करें',
    'language': 'भाषा',
    'select_language': 'भाषा चुनें',
  },
  bn: {
    // Common
    'dashboard': 'ড্যাশবোর্ড',
    'appointments': 'অ্যাপয়েন্টমেন্ট',
    'prescriptions': 'প্রেসক্রিপশন',
    'settings': 'সেটিংস',
    'logout': 'লগআউট',
    'save': 'সংরক্ষণ',
    'cancel': 'বাতিল',
    'edit': 'সম্পাদনা',
    'delete': 'মুছে ফেলুন',
    'view': 'দেখুন',
    'status': 'অবস্থা',
    'date': 'তারিখ',
    'time': 'সময়',
    'doctor': 'ডাক্তার',
    'patient': 'রোগী',
    'name': 'নাম',
    'email': 'ইমেইল',
    'phone': 'ফোন',
    'address': 'ঠিকানা',
    'emergency_contact': 'জরুরি যোগাযোগ',
    'relationship': 'সম্পর্ক',
    'notifications': 'বিজ্ঞপ্তি',
    'security': 'নিরাপত্তা',
    'profile': 'প্রোফাইল',
    'change_password': 'পাসওয়ার্ড পরিবর্তন',
    'current_password': 'বর্তমান পাসওয়ার্ড',
    'new_password': 'নতুন পাসওয়ার্ড',
    'confirm_password': 'পাসওয়ার্ড নিশ্চিত করুন',
    'update_password': 'পাসওয়ার্ড আপডেট',
    'two_factor_auth': 'দুই-ফ্যাক্টর প্রমাণીকরণ',
    'enable_2fa': '2FA সক্রিয় করুন',
    'language': 'ভাষা',
    'select_language': 'ভাষা নির্বাচন করুন',
  },
  ta: {
    // Common
    'dashboard': 'டாஷ்போர்டு',
    'appointments': 'நேரமுன்னேற்பாடுகள்',
    'prescriptions': 'மருந்துச்சீட்டுகள்',
    'settings': 'அமைப்புகள்',
    'logout': 'வெளியேறு',
    'save': 'சேமி',
    'cancel': 'ரத்து செய்',
    'edit': 'திருத்து',
    'delete': 'அழி',
    'view': 'காண்க',
    'status': 'நிலை',
    'date': 'தேதி',
    'time': 'நேரம்',
    'doctor': 'மருத்துவர்',
    'patient': 'நோயாளி',
    'name': 'பெயர்',
    'email': 'மின்னஞ்சல்',
    'phone': 'தொலைபேசி',
    'address': 'முகவரி',
    'emergency_contact': 'அவசர தொடர்பு',
    'relationship': 'உறவு',
    'notifications': 'அறிவிப்புகள்',
    'security': 'பாதுகாப்பு',
    'profile': 'சுயவிவரம்',
    'change_password': 'கடவுச்சொல் மாற்று',
    'current_password': 'தற்போதைய கடவுச்சொல்',
    'new_password': 'புதிய கடவுச்சொல்',
    'confirm_password': 'கடவுச்சொல் உறுதிப்படுத்து',
    'update_password': 'கடவுச்சொல் புதுப்பி',
    'two_factor_auth': 'இரண்டு காரணி அங்கீகாரம்',
    'enable_2fa': '2FA இயக்கு',
    'language': 'மொழி',
    'select_language': 'மொழியைத் தேர்வு செய்க',
  },
  te: {
    // Common
    'dashboard': 'డాష్‌బోర్డ్',
    'appointments': 'అపాయింట్‌మెంట్‌లు',
    'prescriptions': 'ప్రిస్క్రిప్షన్‌లు',
    'settings': 'సెట్టింగ్‌లు',
    'logout': 'లాగ్‌అవుట్',
    'save': 'సేవ్',
    'cancel': 'రద్దు',
    'edit': 'సవరించు',
    'delete': 'తొలగించు',
    'view': 'చూడండి',
    'status': 'స్థితి',
    'date': 'తేదీ',
    'time': 'సమయం',
    'doctor': 'డాక్టర్',
    'patient': 'రోగి',
    'name': 'పేరు',
    'email': 'ఇమెయిల్',
    'phone': 'ఫోన్',
    'address': 'చిరునామా',
    'emergency_contact': 'అత్యవసర సంప్రదింపు',
    'relationship': 'సంబంధం',
    'notifications': 'నోటిఫికేషన్‌లు',
    'security': 'భద్రత',
    'profile': 'ప్రొఫైల్',
    'change_password': 'పాస్‌వర్డ్ మార్చండి',
    'current_password': 'ప్రస్తుత పాస్‌వర్డ్',
    'new_password': 'కొత్త పాస్‌వర్డ్',
    'confirm_password': 'పాస్‌వర్డ్ నిర్ధారించండి',
    'update_password': 'పాస్‌వర్డ్ అప్‌డేట్',
    'two_factor_auth': 'రెండు-కారక ప్రమాణీకరణ',
    'enable_2fa': '2FA ప్రారంభించండి',
    'language': 'భాష',
    'select_language': 'భాషను ఎంచుకోండి',
  },
  mr: {
    // Common
    'dashboard': 'डॅशबोर्ड',
    'appointments': 'अपॉइंटमेंट',
    'prescriptions': 'प्रिस्क्रिप्शन',
    'settings': 'सेटिंग्ज',
    'logout': 'लॉगआउट',
    'save': 'जतन करा',
    'cancel': 'रद्द करा',
    'edit': 'संपादित करा',
    'delete': 'हटवा',
    'view': 'पहा',
    'status': 'स्थिती',
    'date': 'तारीख',
    'time': 'वेळ',
    'doctor': 'डॉक्टर',
    'patient': 'रुग्ण',
    'name': 'नाव',
    'email': 'ईमेल',
    'phone': 'फोन',
    'address': 'पत्ता',
    'emergency_contact': 'आपत्कालीन संपर्क',
    'relationship': 'नाते',
    'notifications': 'सूचना',
    'security': 'सुरक्षा',
    'profile': 'प्रोफाइल',
    'change_password': 'पासवर्ड बदला',
    'current_password': 'सध्याचा पासवर्ड',
    'new_password': 'नवीन पासवर्ड',
    'confirm_password': 'पासवर्डची पुष्टी करा',
    'update_password': 'पासवर्ड अपडेट करा',
    'two_factor_auth': 'द्वि-कारक प्रमाणीकरण',
    'enable_2fa': '2FA सक्षम करा',
    'language': 'भाषा',
    'select_language': 'भाषा निवडा',
  },
  gu: {
    // Common
    'dashboard': 'ડેશબોર્ડ',
    'appointments': 'એપોઇન્ટમેન્ટ',
    'prescriptions': 'પ્રિસ્ક્રિપ્શન',
    'settings': 'સેટિંગ્સ',
    'logout': 'લોગઆઉટ',
    'save': 'સાચવો',
    'cancel': 'રદ કરો',
    'edit': 'સંપાદિત કરો',
    'delete': 'કાઢી નાખો',
    'view': 'જુઓ',
    'status': 'સ્થિતિ',
    'date': 'તારીખ',
    'time': 'સમય',
    'doctor': 'ડૉક્ટર',
    'patient': 'દર્દી',
    'name': 'નામ',
    'email': 'ઈમેલ',
    'phone': 'ફોન',
    'address': 'સરનામું',
    'emergency_contact': 'અનટાઇમ સંપર્ક',
    'relationship': 'સંબંધ',
    'notifications': 'સૂચના',
    'security': 'સુરક્ષા',
    'profile': 'પ્રોફાઇલ',
    'change_password': 'પાસવર્ડ બદલો',
    'current_password': 'વર્તમાન પાસવર્ડ',
    'new_password': 'નવો પાસવર્ડ',
    'confirm_password': 'પાસવર્ડની પુષ્ટિ કરો',
    'update_password': 'પાસવર્ડ અપડેટ કરો',
    'two_factor_auth': 'બે-કારક પ્રમાણીકરણ',
    'enable_2fa': '2FA સક્ષમ કરો',
    'language': 'ભાષા',
    'select_language': 'ભાષા પસંદ કરો',
  },
  kn: {
    // Common
    'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'appointments': 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು',
    'prescriptions': 'ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳು',
    'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'logout': 'ಲಾಗ್‌ಔಟ್',
    'save': 'ಉಳಿಸಿ',
    'cancel': 'ರದ್ದುಮಾಡಿ',
    'edit': 'ಸಂಪಾದಿಸಿ',
    'delete': 'ಅಳಿಸಿ',
    'view': 'ನೋಡಿ',
    'status': 'ಸ್ಥಿತಿ',
    'date': 'ದಿನಾಂಕ',
    'time': 'ಸಮಯ',
    'doctor': 'ವೈದ್ಯ',
    'patient': 'ರೋಗಿ',
    'name': 'ಹೆಸರು',
    'email': 'ಇಮೇಲ್',
    'phone': 'ಫೋನ್',
    'address': 'ವಿಳಾಸ',
    'emergency_contact': 'ಅತ್ಯವಸರ ಸಂಪರ್ಕ',
    'relationship': 'ಸಂಬಂಧ',
    'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'security': 'ಭದ್ರತೆ',
    'profile': 'ಪ್ರೊಫೈಲ್',
    'change_password': 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ',
    'current_password': 'ಪ್ರಸ್ತುತ ಪಾಸ್‌ವರ್ಡ್',
    'new_password': 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್',
    'confirm_password': 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    'update_password': 'ಪಾಸ್‌ವರ್ಡ್ ಅಪ್‌ಡೇಟ್',
    'two_factor_auth': 'ಎರಡು-ಅಂಶ ದೃಢೀಕರಣ',
    'enable_2fa': '2FA ಸಕ್ರಿಯಗೊಳಿಸಿ',
    'language': 'ಭಾಷೆ',
    'select_language': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
  },
  ml: {
    // Common
    'dashboard': 'ഡാഷ്‌ബോർഡ്',
    'appointments': 'അപ്പോയിന്റ്‌മെന്റുകൾ',
    'prescriptions': 'പ്രിസ്ക്രിപ്ഷനുകൾ',
    'settings': 'സെറ്റിംഗുകൾ',
    'logout': 'ലോഗൗട്ട്',
    'save': 'സംരക്ഷിക്കുക',
    'cancel': 'റദ്ദാക്കുക',
    'edit': 'എഡിറ്റ് ചെയ്യുക',
    'delete': 'ഇല്ലാതാക്കുക',
    'view': 'കാണുക',
    'status': 'നില',
    'date': 'തീയതി',
    'time': 'സമയം',
    'doctor': 'ഡോക്ടർ',
    'patient': 'രോഗി',
    'name': 'പേര്',
    'email': 'ഇമെയിൽ',
    'phone': 'ഫോൺ',
    'address': 'വിലാസം',
    'emergency_contact': 'അടിയന്തര ബന്ധം',
    'relationship': 'ബന്ധം',
    'notifications': 'അറിയിപ്പുകൾ',
    'security': 'സുരക്ഷ',
    'profile': 'പ്രൊഫൈൽ',
    'change_password': 'പാസ്‌വേഡ് മാറ്റുക',
    'current_password': 'നിലവിലെ പാസ്‌വേഡ്',
    'new_password': 'പുതിയ പാസ്‌വേഡ്',
    'confirm_password': 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    'update_password': 'പാസ്‌വേഡ് അപ്‌ഡേറ്റ്',
    'two_factor_auth': 'രണ്ട്-ഘടക പ്രമാണീകരണം',
    'enable_2fa': '2FA പ്രവർത്തനക്ഷമമാക്കുക',
    'language': 'ഭാഷ',
    'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
  },
  pa: {
    // Common
    'dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'appointments': 'ਅਪਾਇੰਟਮੈਂਟ',
    'prescriptions': 'ਪ੍ਰੈਸਕ੍ਰਿਪਸ਼ਨ',
    'settings': 'ਸੈਟਿੰਗਾਂ',
    'logout': 'ਲੌਗਆਉਟ',
    'save': 'ਸੇਵ ਕਰੋ',
    'cancel': 'ਰੱਦ ਕਰੋ',
    'edit': 'ਸੰਪਾਦਿਤ ਕਰੋ',
    'delete': 'ਹਟਾਓ',
    'view': 'ਦੇਖੋ',
    'status': 'ਸਥਿਤੀ',
    'date': 'ਮਿਤੀ',
    'time': 'ਸਮਾਂ',
    'doctor': 'ਡਾਕਟਰ',
    'patient': 'ਮਰੀਜ਼',
    'name': 'ਨਾਮ',
    'email': 'ਈਮੇਲ',
    'phone': 'ਫੋਨ',
    'address': 'ਪਤਾ',
    'emergency_contact': 'ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ',
    'relationship': 'ਰਿਸ਼ਤਾ',
    'notifications': 'ਸੂਚਨਾਵਾਂ',
    'security': 'ਸੁਰੱਖਿਆ',
    'profile': 'ਪ੍ਰੋਫਾਈਲ',
    'change_password': 'ਪਾਸਵਰਡ ਬਦਲੋ',
    'current_password': 'ਮੌਜੂਦਾ ਪਾਸਵਰਡ',
    'new_password': 'ਨਵਾਂ ਪਾਸਵਰਡ',
    'confirm_password': 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    'update_password': 'ਪਾਸਵਰਡ ਅਪਡੇਟ ਕਰੋ',
    'two_factor_auth': 'ਦੋ-ਕਾਰਕ ਪ੍ਰਮਾਣੀਕਰਣ',
    'enable_2fa': '2FA ਸਮਰੱਥ ਕਰੋ',
    'language': 'ਭਾਸ਼ਾ',
    'select_language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 